trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
# Install NuGet (Ensures you have the latest version)
- task: NuGetToolInstaller@1

# Restore NuGet Packages
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# Build the Project
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- script: curl https://api.ipify.org
  displayName: 'Get Agent IP Address'



# Apply Database Migrations
- task: DotNetCoreCLI@2
  displayName: 'Apply Migrations'
  inputs:
    command: 'exec'
    projects: '**/*.csproj'
    arguments: 'database update'

# Run Integration Tests
- script: |
    echo "Running integration tests"
    dotnet test --filter TestCategory=Integration
  env:
    ConnectionStrings__Default: $(ConnectionStrings__Default)
    
# Publish the Output as an Artifact
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'

# Deploy to Azure App Service
- task: AzureWebApp@1
  displayName: 'Deploy to Azure App Service'
  inputs:
    azureSubscription: 'tempusServiceConnection'
    appType: 'webApp'
    appName: 'jgsaldana4'
    package: '$(Build.ArtifactStagingDirectory)\WebApp.zip'
